### ISSUE TITLE
Publish.ps1 should have a default value for APIKey so that it doesn't require the user to enter it every time.

### ISSUE THREAD

**Issue by MarkMichaelis** [IntelliTect/PSToolbox#14]

**Comment by adamskt** [comment]
I would strongly argue against this.  Providing a default value would mean checking in the API key into publicly-visible code, which means anyone could impersonate IntelliTect on PS Gallery.  Is there a way to cache a simple string in the Windows Credential Store, so that a publisher will only be prompted once in a session?

**Comment by MarkMichaelis** [comment]
Certainly... didn't even occur to me to do otherwise.  I was assuming the default value was pulled from another source like Credential Store as you suggested.... not something we would hard code.  Andrew believes he saw something like this as part of PowerShell Gallery but if not, we will use the credential store or some local machine mechanism.

**Comment by ascott18** [comment]
Added integration with IntelliTect.CredentialManager if it is installed/imported in eaca2b7. 
Add the API key using `Set-CredentialManagerCredential psgallery` (make the username whatever you want; it isn't used)
